### ISSUE TITLE
Does not extract as ogg

### ISSUE THREAD

**Issue by assassinscrack** [Twigzie/Fantality-LostArkAudioExtractor#4]
Hey and thanks for your work, I wanted to report what I have found using the tool.

It will always extract as mp3 no matter which option picked.
When selecting ogg it will open the right folder but the files will be in the mp3 folder, as mp3s.

Additionally, on some files it will partially extract like this "DDNLVOV23Z8SA3M17H0H7HA3EO7S2_decrypted_292.mp3".

Not a big deal as the others have no information besides the deobfuscated name of the sound bank anyway, but wanted to mention it.

I was hoping it'd extract the files with more naming and info about what they do (like emote_happy, skill_dissonance, player_resurrect_1 etc.) but I don't know how that would be done.

I assume that will require some additional steps.

**Comment by Twigzie** [comment]
Thanks, I've noticed a few issues myself. I was just using the already created batch files that were supplied via the Wwise tool. I'll look into it and see if I can ditch the original batch files so I can have more control over the process.

I think ill incorporate both tools into the explorer I'm working on. A file explorer for Lost Ark that displays a directory structure with names deobfuscated. I could easily add the option to extract audio if the file is supported. example:

![Screenshot 2024-05-02 131153](https://github.com/Twigzie/Fantality-LostArkAudioExtractor/assets/1693796/8f56c3cc-e48f-4997-b06b-c80ab7d4e0b4)

**Comment by assassinscrack** [comment]
Wow this is looking really good. Glad to hear you are still working on it.

I think the ability to extract audio would be a great addition to the explorer.
To be able to export in a useful format.. That's exactly what I have been wanting to do.
Can't wait to try out the tool when it's ready.

**Comment by Twigzie** [comment]
Yea, it's just the fact that the game has over 30K files that makes it not so simple XD

**Comment by assassinscrack** [comment]
I can imagine, with a game of this size.. If you need some product testing done on the work in progress let me know^^

Otherwise do you think you can make a pre-release or a simple batch file available in the near future?
Something to extract the audio files with names like in in that picture you posted?

**Comment by Twigzie** [comment]
> If you need some product testing done on the work in progress let me know^^

Sure, I'm always up for free testing XD

> extract the audio files with names like in that picture you posted?

I use the same function that the "renamer" uses to rename the files. Thats all the posted picture is doing. Renaming the audio files (in the application, not the original files). Its just done with all files and not just single files. Nothing different, except me not wanting to force the user to rename all original files which would break their game.

check my profile for my discord name. shoot me a friend request and ill send you builds to test when they're available for testing

**Comment by Twigzie** [comment]
Updated version [Here](https://github.com/Twigzie/Fantality-LostArkAudioExtractor/releases/tag/v2024.0511.91.0004)

**Comment by assassinscrack** [comment]
> check my profile for my discord name. shoot me a friend request and ill send you builds to test when they're available for testing

The discord link doesn't seem to work so I just dropped my name in my bio maybe you can add me

**Comment by Twigzie** [comment]
Im going to assume the last update fixed the issue. Ill close it, if not, please reopen.
